### ISSUE TITLE
codeblocks project files

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/DXF_Viewer#34]
@asmwarrior Do you use and maintain the codeblocks project files  in this repo?

https://github.com/JamesBremner/DXF_Viewer/tree/master/codeblocks

( BTW thank you for diligently maintaining the wxWidgets code )

**Comment by asmwarrior** [comment]
In fact, I use my own Code::Blocks cbp file, because I use msys2/gcc compiler, and the wxWidgets library is install in the msys2 by the pacman command. So, the cbp file is not the same as the one in the repo. If you like, I can share that cbp file.

**Comment by JamesBremner** [comment]
I would appreciate it if you would take over the maintenance of the codeblocks project files.

I believe it would make things simpler for you in that you would no longer need to keep your codeblock project file in some other repo.

If you wish, you need only maintain the wxWidgets build.

> I use msys2/gcc compiler, and the wxWidgets library is install in the msys2 by the pacman command.

This is how I do it also.

**Comment by asmwarrior** [comment]
OK, I will make a pull request tomorrow.

**Comment by asmwarrior** [comment]
[Code::Blocks project: use the msys2's wxWidgets library to build the … by asmwarrior · Pull Request #36 · JamesBremner/DXF_Viewer](https://github.com/JamesBremner/DXF_Viewer/pull/36)

This is the PR to adjust the wxWidgets cbp to use msys2's wxWidgets library.

Note the wx-config-msys2.exe is needed, and it can be generated from this project: https://github.com/eranif/wx-config-msys2
When you have this exe file, you can put the exe file in the PATH or in the same folder of the cbp file, so that when compiling or linking, the correct option can be generated.

**Comment by JamesBremner** [comment]
See my comment on the `resource.rc` commit.

> Note the ...

This looks like something that should be in a `README` in the codeblocks folder.

**Comment by JamesBremner** [comment]
Pull request merged ( it got mixed up in #36 )
